apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ec2
  name: ec2-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ec2
  template:
    metadata:
      labels:
        app: ec2
    spec:
      containers:
      - name: cont1
        image: mdinesh28/ec2
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aws
spec:
  type: LoadBalancer
  selector:
    app: ec2
  ports:
    - port: 80
      targetPort: 80
