apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vpc
  name: vpc-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vpc
  template:
    metadata:
      labels:
        app: vpc
    spec:
      containers:
      - name: cont1
        image: mdinesh28/netflix
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aws
spec:
  type: LoadBalancer
  selector:
    app: vpc
  ports:
    - port: 80
      targetPort: 80
